<?php

namespace Proxies\__CG__\principalBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PhpposCustomers extends \principalBundle\Entity\PhpposCustomers implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'accountNumber', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'overrideDefaultTax', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'companyName', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'balance', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'creditLimit', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'points', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'currentSpendForPoints', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'currentSalesForDiscount', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'taxable', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'taxCertificate', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'ccToken', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'ccPreview', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'cardIssuer', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'deleted', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'id', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'tier', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'person'];
        }

        return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'accountNumber', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'overrideDefaultTax', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'companyName', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'balance', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'creditLimit', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'points', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'currentSpendForPoints', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'currentSalesForDiscount', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'taxable', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'taxCertificate', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'ccToken', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'ccPreview', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'cardIssuer', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'deleted', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'id', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'tier', '' . "\0" . 'principalBundle\\Entity\\PhpposCustomers' . "\0" . 'person'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PhpposCustomers $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setAccountNumber($accountNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccountNumber', [$accountNumber]);

        return parent::setAccountNumber($accountNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountNumber', []);

        return parent::getAccountNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setOverrideDefaultTax($overrideDefaultTax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOverrideDefaultTax', [$overrideDefaultTax]);

        return parent::setOverrideDefaultTax($overrideDefaultTax);
    }

    /**
     * {@inheritDoc}
     */
    public function getOverrideDefaultTax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOverrideDefaultTax', []);

        return parent::getOverrideDefaultTax();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyName($companyName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyName', [$companyName]);

        return parent::setCompanyName($companyName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyName', []);

        return parent::getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    public function setBalance($balance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBalance', [$balance]);

        return parent::setBalance($balance);
    }

    /**
     * {@inheritDoc}
     */
    public function getBalance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalance', []);

        return parent::getBalance();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreditLimit($creditLimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreditLimit', [$creditLimit]);

        return parent::setCreditLimit($creditLimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditLimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditLimit', []);

        return parent::getCreditLimit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoints($points)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoints', [$points]);

        return parent::setPoints($points);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoints()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoints', []);

        return parent::getPoints();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentSpendForPoints($currentSpendForPoints)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentSpendForPoints', [$currentSpendForPoints]);

        return parent::setCurrentSpendForPoints($currentSpendForPoints);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentSpendForPoints()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentSpendForPoints', []);

        return parent::getCurrentSpendForPoints();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentSalesForDiscount($currentSalesForDiscount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentSalesForDiscount', [$currentSalesForDiscount]);

        return parent::setCurrentSalesForDiscount($currentSalesForDiscount);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentSalesForDiscount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentSalesForDiscount', []);

        return parent::getCurrentSalesForDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxable($taxable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxable', [$taxable]);

        return parent::setTaxable($taxable);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxable', []);

        return parent::getTaxable();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxCertificate($taxCertificate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxCertificate', [$taxCertificate]);

        return parent::setTaxCertificate($taxCertificate);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxCertificate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxCertificate', []);

        return parent::getTaxCertificate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCcToken($ccToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCcToken', [$ccToken]);

        return parent::setCcToken($ccToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getCcToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCcToken', []);

        return parent::getCcToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setCcPreview($ccPreview)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCcPreview', [$ccPreview]);

        return parent::setCcPreview($ccPreview);
    }

    /**
     * {@inheritDoc}
     */
    public function getCcPreview()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCcPreview', []);

        return parent::getCcPreview();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardIssuer($cardIssuer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardIssuer', [$cardIssuer]);

        return parent::setCardIssuer($cardIssuer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardIssuer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardIssuer', []);

        return parent::getCardIssuer();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', [$deleted]);

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', []);

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTier(\principalBundle\Entity\PhpposPriceTiers $tier = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTier', [$tier]);

        return parent::setTier($tier);
    }

    /**
     * {@inheritDoc}
     */
    public function getTier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTier', []);

        return parent::getTier();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerson(\principalBundle\Entity\PhpposPeople $person = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerson', [$person]);

        return parent::setPerson($person);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerson', []);

        return parent::getPerson();
    }

}
