<?php

namespace Proxies\__CG__\principalBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PhpposGiftcardsLog extends \principalBundle\Entity\PhpposGiftcardsLog implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposGiftcardsLog' . "\0" . 'logDate', '' . "\0" . 'principalBundle\\Entity\\PhpposGiftcardsLog' . "\0" . 'transactionAmount', '' . "\0" . 'principalBundle\\Entity\\PhpposGiftcardsLog' . "\0" . 'logMessage', '' . "\0" . 'principalBundle\\Entity\\PhpposGiftcardsLog' . "\0" . 'id', '' . "\0" . 'principalBundle\\Entity\\PhpposGiftcardsLog' . "\0" . 'giftcard'];
        }

        return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposGiftcardsLog' . "\0" . 'logDate', '' . "\0" . 'principalBundle\\Entity\\PhpposGiftcardsLog' . "\0" . 'transactionAmount', '' . "\0" . 'principalBundle\\Entity\\PhpposGiftcardsLog' . "\0" . 'logMessage', '' . "\0" . 'principalBundle\\Entity\\PhpposGiftcardsLog' . "\0" . 'id', '' . "\0" . 'principalBundle\\Entity\\PhpposGiftcardsLog' . "\0" . 'giftcard'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PhpposGiftcardsLog $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setLogDate($logDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogDate', [$logDate]);

        return parent::setLogDate($logDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogDate', []);

        return parent::getLogDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransactionAmount($transactionAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransactionAmount', [$transactionAmount]);

        return parent::setTransactionAmount($transactionAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactionAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactionAmount', []);

        return parent::getTransactionAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogMessage($logMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogMessage', [$logMessage]);

        return parent::setLogMessage($logMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogMessage', []);

        return parent::getLogMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGiftcard(\principalBundle\Entity\PhpposGiftcards $giftcard = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGiftcard', [$giftcard]);

        return parent::setGiftcard($giftcard);
    }

    /**
     * {@inheritDoc}
     */
    public function getGiftcard()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGiftcard', []);

        return parent::getGiftcard();
    }

}
