<?php

namespace Proxies\__CG__\principalBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PhpposEmployees extends \principalBundle\Entity\PhpposEmployees implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'username', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'password', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'forcePasswordChange', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'language', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'commissionPercent', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'commissionPercentType', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'hourlyPayRate', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'inactive', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'reasonInactive', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'hireDate', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'employeeNumber', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'birthday', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'terminationDate', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'deleted', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'id', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'person', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'module', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'location'];
        }

        return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'username', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'password', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'forcePasswordChange', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'language', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'commissionPercent', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'commissionPercentType', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'hourlyPayRate', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'inactive', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'reasonInactive', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'hireDate', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'employeeNumber', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'birthday', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'terminationDate', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'deleted', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'id', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'person', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'module', '' . "\0" . 'principalBundle\\Entity\\PhpposEmployees' . "\0" . 'location'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PhpposEmployees $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setForcePasswordChange($forcePasswordChange)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForcePasswordChange', [$forcePasswordChange]);

        return parent::setForcePasswordChange($forcePasswordChange);
    }

    /**
     * {@inheritDoc}
     */
    public function getForcePasswordChange()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForcePasswordChange', []);

        return parent::getForcePasswordChange();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage($language)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', [$language]);

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', []);

        return parent::getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommissionPercent($commissionPercent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommissionPercent', [$commissionPercent]);

        return parent::setCommissionPercent($commissionPercent);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommissionPercent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommissionPercent', []);

        return parent::getCommissionPercent();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommissionPercentType($commissionPercentType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommissionPercentType', [$commissionPercentType]);

        return parent::setCommissionPercentType($commissionPercentType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommissionPercentType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommissionPercentType', []);

        return parent::getCommissionPercentType();
    }

    /**
     * {@inheritDoc}
     */
    public function setHourlyPayRate($hourlyPayRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHourlyPayRate', [$hourlyPayRate]);

        return parent::setHourlyPayRate($hourlyPayRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getHourlyPayRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHourlyPayRate', []);

        return parent::getHourlyPayRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setInactive($inactive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInactive', [$inactive]);

        return parent::setInactive($inactive);
    }

    /**
     * {@inheritDoc}
     */
    public function getInactive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInactive', []);

        return parent::getInactive();
    }

    /**
     * {@inheritDoc}
     */
    public function setReasonInactive($reasonInactive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReasonInactive', [$reasonInactive]);

        return parent::setReasonInactive($reasonInactive);
    }

    /**
     * {@inheritDoc}
     */
    public function getReasonInactive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReasonInactive', []);

        return parent::getReasonInactive();
    }

    /**
     * {@inheritDoc}
     */
    public function setHireDate($hireDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHireDate', [$hireDate]);

        return parent::setHireDate($hireDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getHireDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHireDate', []);

        return parent::getHireDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployeeNumber($employeeNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployeeNumber', [$employeeNumber]);

        return parent::setEmployeeNumber($employeeNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployeeNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployeeNumber', []);

        return parent::getEmployeeNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthday($birthday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthday', [$birthday]);

        return parent::setBirthday($birthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', []);

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerminationDate($terminationDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerminationDate', [$terminationDate]);

        return parent::setTerminationDate($terminationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getTerminationDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerminationDate', []);

        return parent::getTerminationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', [$deleted]);

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', []);

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerson(\principalBundle\Entity\PhpposPeople $person = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerson', [$person]);

        return parent::setPerson($person);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerson', []);

        return parent::getPerson();
    }

    /**
     * {@inheritDoc}
     */
    public function addModule(\principalBundle\Entity\PhpposModules $module)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addModule', [$module]);

        return parent::addModule($module);
    }

    /**
     * {@inheritDoc}
     */
    public function removeModule(\principalBundle\Entity\PhpposModules $module)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeModule', [$module]);

        return parent::removeModule($module);
    }

    /**
     * {@inheritDoc}
     */
    public function getModule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModule', []);

        return parent::getModule();
    }

    /**
     * {@inheritDoc}
     */
    public function addLocation(\principalBundle\Entity\PhpposLocations $location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLocation', [$location]);

        return parent::addLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLocation(\principalBundle\Entity\PhpposLocations $location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLocation', [$location]);

        return parent::removeLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

}
