<?php

namespace Proxies\__CG__\principalBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PhpposSalesPayments extends \principalBundle\Entity\PhpposSalesPayments implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'paymentType', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'paymentAmount', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'authCode', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'refNo', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'ccToken', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'acqRefData', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'processData', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'entryMethod', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'aid', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'tvr', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'iad', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'tsi', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'arc', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'cvm', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'tranType', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'applicationLabel', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'truncatedCard', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'cardIssuer', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'paymentDate', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'paymentId', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'sale'];
        }

        return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'paymentType', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'paymentAmount', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'authCode', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'refNo', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'ccToken', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'acqRefData', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'processData', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'entryMethod', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'aid', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'tvr', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'iad', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'tsi', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'arc', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'cvm', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'tranType', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'applicationLabel', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'truncatedCard', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'cardIssuer', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'paymentDate', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'paymentId', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesPayments' . "\0" . 'sale'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PhpposSalesPayments $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPaymentType($paymentType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentType', [$paymentType]);

        return parent::setPaymentType($paymentType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentType', []);

        return parent::getPaymentType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentAmount($paymentAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentAmount', [$paymentAmount]);

        return parent::setPaymentAmount($paymentAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentAmount', []);

        return parent::getPaymentAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthCode($authCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthCode', [$authCode]);

        return parent::setAuthCode($authCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthCode', []);

        return parent::getAuthCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefNo($refNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefNo', [$refNo]);

        return parent::setRefNo($refNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefNo', []);

        return parent::getRefNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCcToken($ccToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCcToken', [$ccToken]);

        return parent::setCcToken($ccToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getCcToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCcToken', []);

        return parent::getCcToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setAcqRefData($acqRefData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcqRefData', [$acqRefData]);

        return parent::setAcqRefData($acqRefData);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcqRefData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcqRefData', []);

        return parent::getAcqRefData();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcessData($processData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcessData', [$processData]);

        return parent::setProcessData($processData);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcessData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcessData', []);

        return parent::getProcessData();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntryMethod($entryMethod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntryMethod', [$entryMethod]);

        return parent::setEntryMethod($entryMethod);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntryMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntryMethod', []);

        return parent::getEntryMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setAid($aid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAid', [$aid]);

        return parent::setAid($aid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAid', []);

        return parent::getAid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTvr($tvr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTvr', [$tvr]);

        return parent::setTvr($tvr);
    }

    /**
     * {@inheritDoc}
     */
    public function getTvr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTvr', []);

        return parent::getTvr();
    }

    /**
     * {@inheritDoc}
     */
    public function setIad($iad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIad', [$iad]);

        return parent::setIad($iad);
    }

    /**
     * {@inheritDoc}
     */
    public function getIad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIad', []);

        return parent::getIad();
    }

    /**
     * {@inheritDoc}
     */
    public function setTsi($tsi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTsi', [$tsi]);

        return parent::setTsi($tsi);
    }

    /**
     * {@inheritDoc}
     */
    public function getTsi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTsi', []);

        return parent::getTsi();
    }

    /**
     * {@inheritDoc}
     */
    public function setArc($arc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArc', [$arc]);

        return parent::setArc($arc);
    }

    /**
     * {@inheritDoc}
     */
    public function getArc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArc', []);

        return parent::getArc();
    }

    /**
     * {@inheritDoc}
     */
    public function setCvm($cvm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCvm', [$cvm]);

        return parent::setCvm($cvm);
    }

    /**
     * {@inheritDoc}
     */
    public function getCvm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCvm', []);

        return parent::getCvm();
    }

    /**
     * {@inheritDoc}
     */
    public function setTranType($tranType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTranType', [$tranType]);

        return parent::setTranType($tranType);
    }

    /**
     * {@inheritDoc}
     */
    public function getTranType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTranType', []);

        return parent::getTranType();
    }

    /**
     * {@inheritDoc}
     */
    public function setApplicationLabel($applicationLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApplicationLabel', [$applicationLabel]);

        return parent::setApplicationLabel($applicationLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function getApplicationLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApplicationLabel', []);

        return parent::getApplicationLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setTruncatedCard($truncatedCard)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTruncatedCard', [$truncatedCard]);

        return parent::setTruncatedCard($truncatedCard);
    }

    /**
     * {@inheritDoc}
     */
    public function getTruncatedCard()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTruncatedCard', []);

        return parent::getTruncatedCard();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardIssuer($cardIssuer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardIssuer', [$cardIssuer]);

        return parent::setCardIssuer($cardIssuer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardIssuer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardIssuer', []);

        return parent::getCardIssuer();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentDate($paymentDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentDate', [$paymentDate]);

        return parent::setPaymentDate($paymentDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentDate', []);

        return parent::getPaymentDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPaymentId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentId', []);

        return parent::getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSale(\principalBundle\Entity\PhpposSales $sale = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSale', [$sale]);

        return parent::setSale($sale);
    }

    /**
     * {@inheritDoc}
     */
    public function getSale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSale', []);

        return parent::getSale();
    }

}
