<?php

namespace Proxies\__CG__\principalBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PhpposStoreAccounts extends \principalBundle\Entity\PhpposStoreAccounts implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposStoreAccounts' . "\0" . 'transactionAmount', '' . "\0" . 'principalBundle\\Entity\\PhpposStoreAccounts' . "\0" . 'date', '' . "\0" . 'principalBundle\\Entity\\PhpposStoreAccounts' . "\0" . 'balance', '' . "\0" . 'principalBundle\\Entity\\PhpposStoreAccounts' . "\0" . 'comment', '' . "\0" . 'principalBundle\\Entity\\PhpposStoreAccounts' . "\0" . 'sno', '' . "\0" . 'principalBundle\\Entity\\PhpposStoreAccounts' . "\0" . 'customer', '' . "\0" . 'principalBundle\\Entity\\PhpposStoreAccounts' . "\0" . 'sale'];
        }

        return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposStoreAccounts' . "\0" . 'transactionAmount', '' . "\0" . 'principalBundle\\Entity\\PhpposStoreAccounts' . "\0" . 'date', '' . "\0" . 'principalBundle\\Entity\\PhpposStoreAccounts' . "\0" . 'balance', '' . "\0" . 'principalBundle\\Entity\\PhpposStoreAccounts' . "\0" . 'comment', '' . "\0" . 'principalBundle\\Entity\\PhpposStoreAccounts' . "\0" . 'sno', '' . "\0" . 'principalBundle\\Entity\\PhpposStoreAccounts' . "\0" . 'customer', '' . "\0" . 'principalBundle\\Entity\\PhpposStoreAccounts' . "\0" . 'sale'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PhpposStoreAccounts $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setTransactionAmount($transactionAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransactionAmount', [$transactionAmount]);

        return parent::setTransactionAmount($transactionAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactionAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactionAmount', []);

        return parent::getTransactionAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setBalance($balance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBalance', [$balance]);

        return parent::setBalance($balance);
    }

    /**
     * {@inheritDoc}
     */
    public function getBalance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalance', []);

        return parent::getBalance();
    }

    /**
     * {@inheritDoc}
     */
    public function setComment($comment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComment', [$comment]);

        return parent::setComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment', []);

        return parent::getComment();
    }

    /**
     * {@inheritDoc}
     */
    public function getSno()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSno();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSno', []);

        return parent::getSno();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer(\principalBundle\Entity\PhpposCustomers $customer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', [$customer]);

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', []);

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setSale(\principalBundle\Entity\PhpposSales $sale = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSale', [$sale]);

        return parent::setSale($sale);
    }

    /**
     * {@inheritDoc}
     */
    public function getSale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSale', []);

        return parent::getSale();
    }

}
