<?php

namespace Proxies\__CG__\principalBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PhpposSalesItemKitsTaxes extends \principalBundle\Entity\PhpposSalesItemKitsTaxes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesItemKitsTaxes' . "\0" . 'cumulative', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesItemKitsTaxes' . "\0" . 'line', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesItemKitsTaxes' . "\0" . 'name', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesItemKitsTaxes' . "\0" . 'percent', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesItemKitsTaxes' . "\0" . 'itemKit', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesItemKitsTaxes' . "\0" . 'sale'];
        }

        return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesItemKitsTaxes' . "\0" . 'cumulative', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesItemKitsTaxes' . "\0" . 'line', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesItemKitsTaxes' . "\0" . 'name', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesItemKitsTaxes' . "\0" . 'percent', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesItemKitsTaxes' . "\0" . 'itemKit', '' . "\0" . 'principalBundle\\Entity\\PhpposSalesItemKitsTaxes' . "\0" . 'sale'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PhpposSalesItemKitsTaxes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCumulative($cumulative)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCumulative', [$cumulative]);

        return parent::setCumulative($cumulative);
    }

    /**
     * {@inheritDoc}
     */
    public function getCumulative()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCumulative', []);

        return parent::getCumulative();
    }

    /**
     * {@inheritDoc}
     */
    public function setLine($line)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLine', [$line]);

        return parent::setLine($line);
    }

    /**
     * {@inheritDoc}
     */
    public function getLine()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getLine();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLine', []);

        return parent::getLine();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getName();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPercent($percent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPercent', [$percent]);

        return parent::setPercent($percent);
    }

    /**
     * {@inheritDoc}
     */
    public function getPercent()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getPercent();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPercent', []);

        return parent::getPercent();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemKit(\principalBundle\Entity\PhpposItemKits $itemKit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemKit', [$itemKit]);

        return parent::setItemKit($itemKit);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemKit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemKit', []);

        return parent::getItemKit();
    }

    /**
     * {@inheritDoc}
     */
    public function setSale(\principalBundle\Entity\PhpposSalesItemKits $sale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSale', [$sale]);

        return parent::setSale($sale);
    }

    /**
     * {@inheritDoc}
     */
    public function getSale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSale', []);

        return parent::getSale();
    }

}
