<?php

namespace Proxies\__CG__\principalBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PhpposReceivingsItems extends \principalBundle\Entity\PhpposReceivingsItems implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'description', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'serialnumber', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'quantityPurchased', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'quantityReceived', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'itemCostPrice', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'itemUnitPrice', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'discountPercent', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'expireDate', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'line', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'receiving', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'item'];
        }

        return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'description', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'serialnumber', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'quantityPurchased', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'quantityReceived', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'itemCostPrice', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'itemUnitPrice', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'discountPercent', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'expireDate', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'line', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'receiving', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivingsItems' . "\0" . 'item'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PhpposReceivingsItems $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerialnumber($serialnumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerialnumber', [$serialnumber]);

        return parent::setSerialnumber($serialnumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerialnumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerialnumber', []);

        return parent::getSerialnumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantityPurchased($quantityPurchased)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantityPurchased', [$quantityPurchased]);

        return parent::setQuantityPurchased($quantityPurchased);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantityPurchased()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantityPurchased', []);

        return parent::getQuantityPurchased();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantityReceived($quantityReceived)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantityReceived', [$quantityReceived]);

        return parent::setQuantityReceived($quantityReceived);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantityReceived()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantityReceived', []);

        return parent::getQuantityReceived();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemCostPrice($itemCostPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemCostPrice', [$itemCostPrice]);

        return parent::setItemCostPrice($itemCostPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemCostPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemCostPrice', []);

        return parent::getItemCostPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemUnitPrice($itemUnitPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemUnitPrice', [$itemUnitPrice]);

        return parent::setItemUnitPrice($itemUnitPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemUnitPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemUnitPrice', []);

        return parent::getItemUnitPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountPercent($discountPercent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountPercent', [$discountPercent]);

        return parent::setDiscountPercent($discountPercent);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountPercent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountPercent', []);

        return parent::getDiscountPercent();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpireDate($expireDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpireDate', [$expireDate]);

        return parent::setExpireDate($expireDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpireDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpireDate', []);

        return parent::getExpireDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLine($line)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLine', [$line]);

        return parent::setLine($line);
    }

    /**
     * {@inheritDoc}
     */
    public function getLine()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getLine();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLine', []);

        return parent::getLine();
    }

    /**
     * {@inheritDoc}
     */
    public function setReceiving(\principalBundle\Entity\PhpposReceivings $receiving)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReceiving', [$receiving]);

        return parent::setReceiving($receiving);
    }

    /**
     * {@inheritDoc}
     */
    public function getReceiving()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReceiving', []);

        return parent::getReceiving();
    }

    /**
     * {@inheritDoc}
     */
    public function setItem(\principalBundle\Entity\PhpposItems $item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItem', [$item]);

        return parent::setItem($item);
    }

    /**
     * {@inheritDoc}
     */
    public function getItem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItem', []);

        return parent::getItem();
    }

}
