<?php

namespace Proxies\__CG__\principalBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PhpposSales extends \principalBundle\Entity\PhpposSales implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'saleTime', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'comment', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'showCommentOnReceipt', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'paymentType', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'ccRefNo', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'authCode', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'deleted', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'suspended', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'storeAccountPayment', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'wasLayaway', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'wasEstimate', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'pointsUsed', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'pointsGained', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'didRedeemDiscount', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'deletedTaxes', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'saleId', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'soldByEmployee', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'register', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'signatureImage', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'tier', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'deletedBy', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'customer', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'location', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'employee'];
        }

        return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'saleTime', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'comment', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'showCommentOnReceipt', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'paymentType', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'ccRefNo', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'authCode', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'deleted', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'suspended', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'storeAccountPayment', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'wasLayaway', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'wasEstimate', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'pointsUsed', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'pointsGained', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'didRedeemDiscount', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'deletedTaxes', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'saleId', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'soldByEmployee', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'register', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'signatureImage', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'tier', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'deletedBy', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'customer', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'location', '' . "\0" . 'principalBundle\\Entity\\PhpposSales' . "\0" . 'employee'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PhpposSales $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setSaleTime($saleTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSaleTime', [$saleTime]);

        return parent::setSaleTime($saleTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getSaleTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSaleTime', []);

        return parent::getSaleTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setComment($comment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComment', [$comment]);

        return parent::setComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment', []);

        return parent::getComment();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowCommentOnReceipt($showCommentOnReceipt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowCommentOnReceipt', [$showCommentOnReceipt]);

        return parent::setShowCommentOnReceipt($showCommentOnReceipt);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowCommentOnReceipt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowCommentOnReceipt', []);

        return parent::getShowCommentOnReceipt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentType($paymentType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentType', [$paymentType]);

        return parent::setPaymentType($paymentType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentType', []);

        return parent::getPaymentType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCcRefNo($ccRefNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCcRefNo', [$ccRefNo]);

        return parent::setCcRefNo($ccRefNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCcRefNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCcRefNo', []);

        return parent::getCcRefNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthCode($authCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthCode', [$authCode]);

        return parent::setAuthCode($authCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthCode', []);

        return parent::getAuthCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', [$deleted]);

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', []);

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuspended($suspended)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuspended', [$suspended]);

        return parent::setSuspended($suspended);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuspended()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuspended', []);

        return parent::getSuspended();
    }

    /**
     * {@inheritDoc}
     */
    public function setStoreAccountPayment($storeAccountPayment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStoreAccountPayment', [$storeAccountPayment]);

        return parent::setStoreAccountPayment($storeAccountPayment);
    }

    /**
     * {@inheritDoc}
     */
    public function getStoreAccountPayment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStoreAccountPayment', []);

        return parent::getStoreAccountPayment();
    }

    /**
     * {@inheritDoc}
     */
    public function setWasLayaway($wasLayaway)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWasLayaway', [$wasLayaway]);

        return parent::setWasLayaway($wasLayaway);
    }

    /**
     * {@inheritDoc}
     */
    public function getWasLayaway()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWasLayaway', []);

        return parent::getWasLayaway();
    }

    /**
     * {@inheritDoc}
     */
    public function setWasEstimate($wasEstimate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWasEstimate', [$wasEstimate]);

        return parent::setWasEstimate($wasEstimate);
    }

    /**
     * {@inheritDoc}
     */
    public function getWasEstimate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWasEstimate', []);

        return parent::getWasEstimate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointsUsed($pointsUsed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointsUsed', [$pointsUsed]);

        return parent::setPointsUsed($pointsUsed);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointsUsed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointsUsed', []);

        return parent::getPointsUsed();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointsGained($pointsGained)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointsGained', [$pointsGained]);

        return parent::setPointsGained($pointsGained);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointsGained()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointsGained', []);

        return parent::getPointsGained();
    }

    /**
     * {@inheritDoc}
     */
    public function setDidRedeemDiscount($didRedeemDiscount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDidRedeemDiscount', [$didRedeemDiscount]);

        return parent::setDidRedeemDiscount($didRedeemDiscount);
    }

    /**
     * {@inheritDoc}
     */
    public function getDidRedeemDiscount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDidRedeemDiscount', []);

        return parent::getDidRedeemDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedTaxes($deletedTaxes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedTaxes', [$deletedTaxes]);

        return parent::setDeletedTaxes($deletedTaxes);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedTaxes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedTaxes', []);

        return parent::getDeletedTaxes();
    }

    /**
     * {@inheritDoc}
     */
    public function getSaleId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSaleId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSaleId', []);

        return parent::getSaleId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoldByEmployee(\principalBundle\Entity\PhpposEmployees $soldByEmployee = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoldByEmployee', [$soldByEmployee]);

        return parent::setSoldByEmployee($soldByEmployee);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoldByEmployee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoldByEmployee', []);

        return parent::getSoldByEmployee();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegister(\principalBundle\Entity\PhpposRegisters $register = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegister', [$register]);

        return parent::setRegister($register);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegister()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegister', []);

        return parent::getRegister();
    }

    /**
     * {@inheritDoc}
     */
    public function setSignatureImage(\principalBundle\Entity\PhpposAppFiles $signatureImage = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignatureImage', [$signatureImage]);

        return parent::setSignatureImage($signatureImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignatureImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignatureImage', []);

        return parent::getSignatureImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setTier(\principalBundle\Entity\PhpposPriceTiers $tier = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTier', [$tier]);

        return parent::setTier($tier);
    }

    /**
     * {@inheritDoc}
     */
    public function getTier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTier', []);

        return parent::getTier();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedBy(\principalBundle\Entity\PhpposEmployees $deletedBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedBy', [$deletedBy]);

        return parent::setDeletedBy($deletedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedBy', []);

        return parent::getDeletedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer(\principalBundle\Entity\PhpposCustomers $customer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', [$customer]);

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', []);

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation(\principalBundle\Entity\PhpposLocations $location = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployee(\principalBundle\Entity\PhpposEmployees $employee = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployee', [$employee]);

        return parent::setEmployee($employee);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployee', []);

        return parent::getEmployee();
    }

}
