<?php

namespace Proxies\__CG__\principalBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PhpposRegisterLog extends \principalBundle\Entity\PhpposRegisterLog implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'shiftStart', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'shiftEnd', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'openAmount', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'closeAmount', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'cashSalesAmount', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'totalCashAdditions', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'totalCashSubtractions', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'notes', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'deleted', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'registerLogId', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'employeeClose', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'register', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'employeeOpen'];
        }

        return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'shiftStart', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'shiftEnd', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'openAmount', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'closeAmount', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'cashSalesAmount', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'totalCashAdditions', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'totalCashSubtractions', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'notes', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'deleted', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'registerLogId', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'employeeClose', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'register', '' . "\0" . 'principalBundle\\Entity\\PhpposRegisterLog' . "\0" . 'employeeOpen'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PhpposRegisterLog $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setShiftStart($shiftStart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShiftStart', [$shiftStart]);

        return parent::setShiftStart($shiftStart);
    }

    /**
     * {@inheritDoc}
     */
    public function getShiftStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShiftStart', []);

        return parent::getShiftStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setShiftEnd($shiftEnd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShiftEnd', [$shiftEnd]);

        return parent::setShiftEnd($shiftEnd);
    }

    /**
     * {@inheritDoc}
     */
    public function getShiftEnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShiftEnd', []);

        return parent::getShiftEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpenAmount($openAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpenAmount', [$openAmount]);

        return parent::setOpenAmount($openAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpenAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpenAmount', []);

        return parent::getOpenAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setCloseAmount($closeAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCloseAmount', [$closeAmount]);

        return parent::setCloseAmount($closeAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getCloseAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCloseAmount', []);

        return parent::getCloseAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setCashSalesAmount($cashSalesAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCashSalesAmount', [$cashSalesAmount]);

        return parent::setCashSalesAmount($cashSalesAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getCashSalesAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCashSalesAmount', []);

        return parent::getCashSalesAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalCashAdditions($totalCashAdditions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalCashAdditions', [$totalCashAdditions]);

        return parent::setTotalCashAdditions($totalCashAdditions);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalCashAdditions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalCashAdditions', []);

        return parent::getTotalCashAdditions();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalCashSubtractions($totalCashSubtractions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalCashSubtractions', [$totalCashSubtractions]);

        return parent::setTotalCashSubtractions($totalCashSubtractions);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalCashSubtractions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalCashSubtractions', []);

        return parent::getTotalCashSubtractions();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotes($notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotes', [$notes]);

        return parent::setNotes($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotes', []);

        return parent::getNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', [$deleted]);

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', []);

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function getRegisterLogId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getRegisterLogId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegisterLogId', []);

        return parent::getRegisterLogId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployeeClose(\principalBundle\Entity\PhpposEmployees $employeeClose = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployeeClose', [$employeeClose]);

        return parent::setEmployeeClose($employeeClose);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployeeClose()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployeeClose', []);

        return parent::getEmployeeClose();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegister(\principalBundle\Entity\PhpposRegisters $register = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegister', [$register]);

        return parent::setRegister($register);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegister()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegister', []);

        return parent::getRegister();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployeeOpen(\principalBundle\Entity\PhpposEmployees $employeeOpen = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployeeOpen', [$employeeOpen]);

        return parent::setEmployeeOpen($employeeOpen);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployeeOpen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployeeOpen', []);

        return parent::getEmployeeOpen();
    }

}
