<?php

namespace Proxies\__CG__\principalBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PhpposModules extends \principalBundle\Entity\PhpposModules implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposModules' . "\0" . 'nameLangKey', '' . "\0" . 'principalBundle\\Entity\\PhpposModules' . "\0" . 'descLangKey', '' . "\0" . 'principalBundle\\Entity\\PhpposModules' . "\0" . 'sort', '' . "\0" . 'principalBundle\\Entity\\PhpposModules' . "\0" . 'icon', '' . "\0" . 'principalBundle\\Entity\\PhpposModules' . "\0" . 'moduleId', '' . "\0" . 'principalBundle\\Entity\\PhpposModules' . "\0" . 'person'];
        }

        return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposModules' . "\0" . 'nameLangKey', '' . "\0" . 'principalBundle\\Entity\\PhpposModules' . "\0" . 'descLangKey', '' . "\0" . 'principalBundle\\Entity\\PhpposModules' . "\0" . 'sort', '' . "\0" . 'principalBundle\\Entity\\PhpposModules' . "\0" . 'icon', '' . "\0" . 'principalBundle\\Entity\\PhpposModules' . "\0" . 'moduleId', '' . "\0" . 'principalBundle\\Entity\\PhpposModules' . "\0" . 'person'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PhpposModules $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNameLangKey($nameLangKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameLangKey', [$nameLangKey]);

        return parent::setNameLangKey($nameLangKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameLangKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameLangKey', []);

        return parent::getNameLangKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescLangKey($descLangKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescLangKey', [$descLangKey]);

        return parent::setDescLangKey($descLangKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescLangKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescLangKey', []);

        return parent::getDescLangKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setSort($sort)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSort', [$sort]);

        return parent::setSort($sort);
    }

    /**
     * {@inheritDoc}
     */
    public function getSort()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSort', []);

        return parent::getSort();
    }

    /**
     * {@inheritDoc}
     */
    public function setIcon($icon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIcon', [$icon]);

        return parent::setIcon($icon);
    }

    /**
     * {@inheritDoc}
     */
    public function getIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIcon', []);

        return parent::getIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function getModuleId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getModuleId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModuleId', []);

        return parent::getModuleId();
    }

    /**
     * {@inheritDoc}
     */
    public function addPerson(\principalBundle\Entity\PhpposEmployees $person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPerson', [$person]);

        return parent::addPerson($person);
    }

    /**
     * {@inheritDoc}
     */
    public function removePerson(\principalBundle\Entity\PhpposEmployees $person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePerson', [$person]);

        return parent::removePerson($person);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerson', []);

        return parent::getPerson();
    }

}
