<?php

namespace Proxies\__CG__\principalBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PhpposReceivings extends \principalBundle\Entity\PhpposReceivings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'receivingTime', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'comment', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'paymentType', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'deleted', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'deletedBy', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'suspended', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'deletedTaxes', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'isPo', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'receivingId', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'transferToLocation', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'location', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'supplier', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'employee'];
        }

        return ['__isInitialized__', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'receivingTime', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'comment', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'paymentType', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'deleted', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'deletedBy', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'suspended', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'deletedTaxes', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'isPo', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'receivingId', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'transferToLocation', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'location', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'supplier', '' . "\0" . 'principalBundle\\Entity\\PhpposReceivings' . "\0" . 'employee'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PhpposReceivings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setReceivingTime($receivingTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReceivingTime', [$receivingTime]);

        return parent::setReceivingTime($receivingTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getReceivingTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReceivingTime', []);

        return parent::getReceivingTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setComment($comment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComment', [$comment]);

        return parent::setComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment', []);

        return parent::getComment();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentType($paymentType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentType', [$paymentType]);

        return parent::setPaymentType($paymentType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentType', []);

        return parent::getPaymentType();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', [$deleted]);

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', []);

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedBy($deletedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedBy', [$deletedBy]);

        return parent::setDeletedBy($deletedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedBy', []);

        return parent::getDeletedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuspended($suspended)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuspended', [$suspended]);

        return parent::setSuspended($suspended);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuspended()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuspended', []);

        return parent::getSuspended();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedTaxes($deletedTaxes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedTaxes', [$deletedTaxes]);

        return parent::setDeletedTaxes($deletedTaxes);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedTaxes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedTaxes', []);

        return parent::getDeletedTaxes();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPo($isPo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPo', [$isPo]);

        return parent::setIsPo($isPo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPo', []);

        return parent::getIsPo();
    }

    /**
     * {@inheritDoc}
     */
    public function getReceivingId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getReceivingId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReceivingId', []);

        return parent::getReceivingId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransferToLocation(\principalBundle\Entity\PhpposLocations $transferToLocation = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransferToLocation', [$transferToLocation]);

        return parent::setTransferToLocation($transferToLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransferToLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransferToLocation', []);

        return parent::getTransferToLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation(\principalBundle\Entity\PhpposLocations $location = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupplier(\principalBundle\Entity\PhpposSuppliers $supplier = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupplier', [$supplier]);

        return parent::setSupplier($supplier);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupplier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupplier', []);

        return parent::getSupplier();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployee(\principalBundle\Entity\PhpposEmployees $employee = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployee', [$employee]);

        return parent::setEmployee($employee);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployee', []);

        return parent::getEmployee();
    }

}
